### ISSUE TITLE
[BUG] Cannot use in conjunction with Dastan's "FavoriteMedia" plugin

### ISSUE THREAD

**Issue by misterpyrrhuloxia** [TheLazySquid/DiscordImageFolder#11]
Trying to run [ImageFolder plugin](https://github.com/TheLazySquid/DiscordImageFolder) in conjunction with @Dastan21's [FavoriteMedia plugin](https://github.com/Dastan21/BDAddons/tree/main/plugins/FavoriteMedia) results of `ImageFolder` completely overriding `FavoriteMedia`'s `Image` tab within the Discord UI, even though `ImageFolder` creates a whole separate tab on the far left called `Images`.

This screenshot demonstrates what I see when I click on either the `ImageFolder` tab or the `Images` tab- clicking on the `Images` tab (orange arrow) does not show any of `FavoriteMedia`'s UI, but only show's `ImageFolder`'s UI, as if its own UI is cloned onto the `FavoriteMedia`'s `Images` tab (green arrow).

![image](https://i.imgur.com/SnyAQ7c.png)

**Comment by TheLazySquid** [comment]
Looks like both plugins used the id 'image' to identify their tab, and ImageFolder took priority for whatever reason. I've switched it to 'if-image', so no more conflict occurs.

**Comment by misterpyrrhuloxia** [comment]
Thank you so much, @TheLazySquid!! When can we expect to see the plugin updated on the BD Repo?

**Comment by TheLazySquid** [comment]
Who knows, it usually takes them from a few days to a few months

**Comment by misterpyrrhuloxia** [comment]
Gotcha, no worries. I just directly downloaded [ImageFolder.plugin.js](https://github.com/TheLazySquid/DiscordImageFolder/raw/main/build/ImageFolder.plugin.js), manually installed it, and it appears to be working now! Thank you so much!!
