### ISSUE TITLE
Would not work

### ISSUE THREAD

**Issue by YoCheng-Liao** [TheLazySquid/DiscordImageFolder#16]
The thing would show up. This is what happens when I click the button:
![image](https://github.com/user-attachments/assets/bbd1e090-c26a-4602-a349-7c522fe20c5b)
It also won't show up as a separate tab when you reach the expression picker normally

This is the console error:
![image](https://github.com/user-attachments/assets/0eaf5cf0-96a9-4694-8617-f673db713329)

**Comment by TheLazySquid** [comment]
Discord updated some stuff, it should be working now
