### ISSUE TITLE
your source buttons lead to a 404 error

### ISSUE THREAD

**Issue by TheGreatTaz** [TheLazySquid/DiscordImageFolder#3]
![image](https://github.com/TheLazySquid/DiscordImageFolder/assets/89170620/6e7265fb-3dad-4b4e-a930-ee7bcc509977)
these buttons contain the wrong links
![image](https://github.com/TheLazySquid/DiscordImageFolder/assets/89170620/64749602-bf97-492c-8899-93615258d163)

**Comment by TheLazySquid** [comment]
Right you are! This should now be fixed.
