### ISSUE TITLE
[Feature/addition Request] AVIF support 

### ISSUE THREAD

**Issue by ItMeSarah** [TheLazySquid/DiscordImageFolder#4]
Would it be possible for you to also add avif for supported image types in the image picker?  The plugin can post them (well, atleast one frame of them, so might not work anyway) if they're in the folder already, but cannot select them with the picker for adding new files, probably cause it's not a supported by discord fike type.

 Additionally, would it be possible to also do videos and sounds as well (would have to rename the plugin to MediaFolder), if that's asking too much I understand.

**Comment by TheLazySquid** [comment]
Not gonna lie, completely forgot that AVIF exists. It should now work. This plugin always re-renders the image as a PNG, so even if discord can't display AVIFs natively, you can still post them with this plugin.

Adding videos and audio sounds like a cool idea, although I can imagine that it'd be a massive pain to try and stream video data from a file. I'll do some experimentation once I finish some other features that are in the works. If I were to add various media types, do you think it would be a good idea to have one folder/tab with all of them, or three separate ones, like FavoriteMedia has?

**Comment by ItMeSarah** [comment]
Nice :) Thanks. yeah, still posts it as a png when it's an animated avifd, but it's a step in the right direction :D

**Comment by TheLazySquid** [comment]
Discord can't display AVIFs, so without re-rending it as a GIF I don't think it'd be possible to make an animated one work.

**Comment by ItMeSarah** [comment]
> Discord can't display AVIFs, so without re-rending it as a GIF I don't think it'd be possible to make an animated one work.

Yeah, there's another plugin that makes them work in Discord, https://betterdiscord.app/plugin/Embed%20More%20Images which is what I use to even see them in discord lol :D

**Comment by ItMeSarah** [comment]
Oh, did you mean to leave a console log in the plugin?  console.log(folder.images);

**Comment by TheLazySquid** [comment]
I've added a setting to allow you disable re-rending the images as pngs. From some testing, it appears to work fine with Embed More Images (even if nobody else can see what the embed).
