### ISSUE TITLE
"Sort By" setting?

### ISSUE THREAD

**Issue by logan97alexander** [TheLazySquid/DiscordImageFolder#5]
Hi, I was wondering if you could add an option to change how the images are sorted in the discord window? Currently my images are being sorted by name regardless of how I sort the folder in my filesystem (I prefer to sort by date, easier to find things I just recently saved). Thanks for making this plugin btw, it's great having something to fall back on since discord borked FavoriteImages :D

**Comment by TheLazySquid** [comment]
Good idea! On the settings panel I've added the option to sort by most recently used, last modified and name. Maybe I'll add some more categories in the future, but these seem like the most useful to me.
