### ISSUE TITLE
Folders don't work

### ISSUE THREAD

**Issue by logan97alexander** [TheLazySquid/DiscordImageFolder#6]
![image](https://github.com/TheLazySquid/DiscordImageFolder/assets/40744117/654d6df8-85d0-464f-b37d-d53c31ff695f)
^ When I open the Image tab in discord, as normal, only files in the base folder appear, plus the subfolders.

![image](https://github.com/TheLazySquid/DiscordImageFolder/assets/40744117/1f3b43dd-4899-4a1e-8bc3-494ac25bce77)
^ When I click the "gif" folder, this happens, continuing to show the files in the base folder without showing the file(s) in the subfolder

**Comment by TheLazySquid** [comment]
Hey! I'm pretty sure I fixed this a bit back, but the official BetterDiscord plugin repo still hasn't accepted the new version. Try downloading the updated version [here](https://github.com/TheLazySquid/DiscordImageFolder/blob/main/build/ImageFolder.plugin.js). If it still doesn't work, tell me whether the images in the subfolder have the same name as those in the main folder.

**Comment by logan97alexander** [comment]
Thanks, but still not working, same problem as before (showing the main folder's files and not the selected subfolder's files). The images in the subfolder have completely different names than any that are in the main folder.

**Comment by TheLazySquid** [comment]
Try disabling FavoriteMedia- that might be interfering with it.

**Comment by logan97alexander** [comment]
No such luck :( I also tried disabling all plugins except ImageFolder and closing & restarting discord, and it didn't change anything.

**Comment by TheLazySquid** [comment]
Could you send me a zip of your folder, so I can do some testing? It should be in your BetterDiscord plugins directory.

**Comment by logan97alexander** [comment]
It was too big to attach here so I put it in google drive [https://drive.google.com/file/d/14T9Dfer0Pb6Y2Bs3AZPQ2_lW4pG_hYeH/view?usp=sharing](https://drive.google.com/file/d/14T9Dfer0Pb6Y2Bs3AZPQ2_lW4pG_hYeH/view?usp=sharing)

**Comment by logan97alexander** [comment]
I don't know why it fixed it for you, but I downloaded the newest version 0.3.2 and am still having the same exact problem :(

**Comment by TheLazySquid** [comment]
Sorry for the late response. Could you try the version of the plugin attached below? It should force stuff to get re-rendered much more aggressively.
[ImageFolder.zip](https://github.com/TheLazySquid/DiscordImageFolder/files/14812166/ImageFolder.zip)

**Comment by logan97alexander** [comment]
Yes, that works perfectly, thank you so much!!

**Comment by TheLazySquid** [comment]
Great! I just pushed a slightly less hacky version of that script.
