### ISSUE TITLE
Image Folder button no longer seems to be added in the channel text area on canary. 

### ISSUE THREAD

**Issue by itmesarah** [TheLazySquid/DiscordImageFolder#7]
`BdApi.Webpack.getModule((m) => m.type?.toString?.().includes("ChannelTextAreaButtons"));` is undefined, looks like the entire section of that module (912823) changed that had that and removed ChannelTextAreaButtons.

`BdApi.Webpack.getModule((m) => m.type?.toString?.().includes(".default.isSubmitButtonEnabled", ".default.getActiveCommand"));` seems to fix it.

**Comment by TheLazySquid** [comment]
Thanks for the fix! Everything seems to work now.
