### ISSUE TITLE
image size should not scale with expression picker window size

### ISSUE THREAD

**Issue by LordFoogThe4rd** [TheLazySquid/DiscordImageFolder#8]
![image](https://github.com/TheLazySquid/DiscordImageFolder/assets/89643664/3504dbd9-908f-4724-a4b9-025a0ae52abc)

image becomes ridiculously big when you expand the picker window

**Comment by TheLazySquid** [comment]
Not gonna lie, I didn't even realize it was able to scale and just harcoded some values. This should be fixed now.
